# Generated by Django 5.2.2 on 2026-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المقال')),
                ('description', models.TextField(verbose_name='محتوى المقال')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='articles/files/', verbose_name='الملف المرفق')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-published_at'],
            },
        ),
    ]
