# Generated by Django 5.2.2 on 2026-07-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, default='وصف عام وبسيط للمقال في جملة واحدة', null=True),
        ),
    ]
