# Generated by Django 5.2.2 on 2026-08-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الكتاب')),
                ('description', models.TextField(verbose_name='وصف الكتاب')),
                ('book_file', models.FileField(upload_to='books/', verbose_name='ملف الكتاب')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'كتاب',
                'verbose_name_plural': 'الكتب',
                'ordering': ['-published_at'],
            },
        ),
    ]
