# Generated by Django 5.2.2 on 2026-08-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(upload_to='books/files/', verbose_name='ملف الكتاب'),
        ),
    ]
