# Generated by Django 5.2.2 on 2026-08-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='books/covers/', verbose_name='صورة الغلاف'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(upload_to='books/', verbose_name='ملف الكتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
