# Generated by Django 5.2.2 on 2026-08-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان البودكاست')),
                ('youtube_url', models.URLField(max_length=500, verbose_name='رابط البودكاست على يوتيوب')),
                ('image', models.ImageField(blank=True, null=True, upload_to='podcast/images/', verbose_name='صورة البودكاست')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'بودكاست',
                'verbose_name_plural': 'البودكاست',
                'ordering': ['-published_at'],
            },
        ),
    ]
