# Generated by Django 5.2.2 on 2026-08-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الدورة')),
                ('link', models.URLField(max_length=500, verbose_name='رابط الدورة')),
                ('thumbnail', models.ImageField(upload_to='courses/thumbnail/', verbose_name='الصورة المصغرة')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
            ],
            options={
                'verbose_name': 'دورة',
                'verbose_name_plural': 'الدورات',
                'ordering': ['-published_at'],
            },
        ),
    ]
