# Generated by Django 5.2.2 on 2026-07-02 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name (English)')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='Category Name (Arabic)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Field Name (English)')),
                ('name_ar', models.CharField(max_length=100, unique=True, verbose_name='Field Name (Arabic)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Field Description')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_other', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='Courses.category', verbose_name='Category related to this field')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['category__order', 'order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Course Title')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='Teacher Name')),
                ('channel_name', models.CharField(blank=True, max_length=100, verbose_name='Channel Name')),
                ('language', models.CharField(max_length=50, verbose_name='Language')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('description', models.TextField(verbose_name='Description')),
                ('link', models.URLField(unique=True, verbose_name='Course Link')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Thumbnail')),
                ('level', models.CharField(choices=[('Beginner', 'مبتدئ'), ('Intermediate', 'متوسط'), ('Advanced', 'متقدم')], default='Beginner', max_length=20, verbose_name='Level')),
                ('is_free', models.BooleanField(default=True, verbose_name='Is Free?')),
                ('certificate', models.BooleanField(default=False, verbose_name='Has Certificate?')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Rating')),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='Courses.category', verbose_name='Category')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='Courses.field', verbose_name='Field')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
    ]
