# Generated by Django 5.2.2 on 2026-07-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
