# Generated by Django 5.2.2 on 2026-07-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_category_icon_svg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Is Active?'),
        ),
    ]
