# Generated by Django 5.2.2 on 2026-06-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZadTech', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='quote',
            new_name='text',
        ),
    ]
